### ISSUE TITLE
Coordinate of getImageData seems to be wrong

### ISSUE THREAD

**Issue by Ovilia** [piqnt/stage.js#26]
I'm using Stage.js to implement a magnifying glass effect like this.

![soap](https://cloud.githubusercontent.com/assets/779050/9309933/34a5141a-453f-11e5-82ae-5188043ee7fc.jpg)

The circle in the top shows the magnified area around mouse position. I tried to read the pixels rendered by Stage.js using `getImageData` but got all 0 in `data`. My code is available [here](https://github.com/Ovilia/qiao/blob/7aba5243e01005be2a7e02d12559aa5e8e80b0d1/src/js/app/main.js#L42).

I'm not sure if transformation of canvas in your game engine changed anything for `getImageData`, but I don't think this should be an issue since canvas spec states:

> The current path, transformation matrix, shadow attributes, global alpha, the clipping region, and global composition operator must not affect the getImageData() and putImageData() methods.

Any idea how should I get the pixels around mouse position in this way? Or, what else game engine should I use to implement this magnifying glass effect?

Thanks!

**Comment by shakiba** [comment]
Have you considered using the canvas create by Stage.js as an image in your second canvas? If you do that you will not need to get and copy image data.

**Comment by Ovilia** [comment]
@shakiba How can I use it as an image? By `toDataURL`?

**Comment by shakiba** [comment]
Just use context as image object. But anyway because canvas is raster, scaling rendered result is going to be pixelated.

Another option is adding a new node type which clones another node and is pinned independently. Therfore your graphics are rendered as they are. But I'm not yet sure how to cut a circle.

**Comment by Ovilia** [comment]
Thanks! It works when I use it as an image. Helped a lot!
